language: python
python:
- 3.6
install:
- pip install -r requirements.txt
script:
- python -m unittest discover
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: w78ZKOGhkbFyr+AjHUNPMWNf4/PqmOgU1LNSKpH/oHb02NbTkpMDbXP2rbOolTYiCthIsyY9bokBATlgH8nDv09QNCMBAVTyYP26k9WxW/PXe3WXD2uBfiy/o+jU5jemFIMJNmv2hS1C0Ua1orhOWCxxgwtXqpFfb6IVsmxkrSuk8CD+hc89uNAVBjf7PFYVlMoXtmkJWnrwY3wa3Ni/EExtNQpA7uzXFis7uAjjrNNF+RrjKg78eTo/FRZWWJiK8CNxPNghNie7Pn2Z1suXm/93IePRgG+V8barDcmrhMHl15wv4vjUK7a+1MFNKRExpJvoIEuIAUqTa0jEt5COzEbwBIAVaZMoyLZYoS2Ql7qTWFM3Vm9OOrDgJOHFGk8cvc4DAVbj7c2lrSQfsZ0TXZiIbkpqKO64rEEineEHVQk0JsNoYhRtSY1ARbWcuEZV89aK7ILdCctaB2P1q3BiMlRVLHNmAnM3fHahF4J2eYRS63cXdm+nVu/GtIjRtDw26Tgq77HFy4CkhSH6DOnYisxOgYQZ3syRkaSuqNuyhNZm6srJd09kizptUv5DXQn+Sv3Ei2k/seoXzaSUJHOdo0o776mN8i0aIQaROxsH2TN8xwDsIoQsZBfFE5eKPz2rq9/DSJZIEqK+VpeCmFOySDFb9Xw+6C+Cw93RiT291sU=
  app: son-translate-chatbot
